export const authCopy = {
  id: {
    language: 'Bahasa',
    login: 'Masuk',
    register: 'Buat akun',
    verify: 'Verifikasi email',
    recover: 'Pulihkan akun',
    setup: 'Buat password',
    reset: 'Ganti password',
    intro: 'Catatan kecil. Ruang milikmu.',
    description: 'Kebiasaan, aktivitas, dan keuangan pribadi, mengikuti ritmemu.',
    loginHelp: 'Masuk untuk melanjutkan catatan harianmu.',
    registerHelp: 'Isi email dan buat password untuk memulai akunmu.',
    registrationSteps: ['Akun', 'Akses terbatas'],
    currentStep: 'Langkah saat ini',
    verifyHelp: 'Masukkan kode 6 digit dari email. Kode hanya berlaku untuk permintaan ini.',
    recoverHelp: 'Masukkan email akunmu untuk meminta kode pemulihan.',
    setupHelp: 'Gunakan password panjang dan unik. Password manager dan paste didukung.',
    resetHelp: 'Tetapkan password baru setelah verifikasi pemulihan.',
    email: 'Email',
    password: 'Password',
    confirm: 'Ulangi password',
    code: 'Kode verifikasi',
    adult: 'Saya berusia 18 tahun atau lebih.',
    send: 'Kirim kode',
    create: 'Buat akun',
    verifyAction: 'Verifikasi kode',
    save: 'Simpan password',
    pending: 'Memproses…',
    resend: 'Kirim ulang kode',
    wait: 'Coba lagi dalam',
    seconds: 'detik',
    forgot: 'Lupa password?',
    haveAccount: 'Sudah punya akun?',
    newAccount: 'Belum punya akun?',
    back: 'Kembali ke login',
    preview: 'Jelajahi pratinjau',
    home: 'Beranda',
    unavailable: 'Layanan akun belum tersedia. Permintaan belum diproses dan akun belum dibuat.',
    notice:
      'Layanan akun belum diaktifkan. Formulir ini tidak akan membuat akun sampai integrasi server siap.',
    devNotice:
      'Pendaftaran tanpa OTP hanya tersedia di server pengembangan lokal untuk email yang diizinkan. Akses fitur produk tetap tertutup.',
    invalid: 'Periksa kembali kolom yang diisi.',
    expired: 'Permintaan verifikasi tidak tersedia atau sudah kedaluwarsa. Mulai lagi dari email.',
    rate_limited: 'Terlalu banyak percobaan. Tunggu sebelum mencoba lagi.',
    credentials: 'Email atau password tidak dapat diverifikasi.',
    network: 'Tidak tersambung. Input belum dikirim; coba lagi.',
    mismatch: 'Kedua password harus sama.',
    passwordHelp:
      'Minimal 15 karakter, maksimal 128 karakter. Jangan gunakan password yang sama dengan layanan lain.',
    sessionRequired:
      'Sesi verifikasi yang valid diperlukan. Buka kembali alur pendaftaran atau pemulihan untuk melanjutkan.',
    continueEmail: 'Mulai dari email',
    show: 'Tampilkan password',
    hide: 'Sembunyikan password',
  },
  en: {
    language: 'Language',
    login: 'Sign in',
    register: 'Create account',
    verify: 'Verify email',
    recover: 'Recover account',
    setup: 'Create password',
    reset: 'Reset password',
    intro: 'Small notes. Your own space.',
    description: 'Habits, activities, and personal finances, at your own pace.',
    loginHelp: 'Sign in to continue your daily notes.',
    registerHelp: 'Enter your email and create a password to get started.',
    registrationSteps: ['Account', 'Limited access'],
    currentStep: 'Current step',
    verifyHelp: 'Enter the 6-digit code from your email. It only applies to this request.',
    recoverHelp: 'Enter your account email to request a recovery code.',
    setupHelp: 'Use a long, unique password. Password managers and paste are supported.',
    resetHelp: 'Set a new password after recovery verification.',
    email: 'Email',
    password: 'Password',
    confirm: 'Confirm password',
    code: 'Verification code',
    adult: 'I am 18 years of age or older.',
    send: 'Send code',
    create: 'Create account',
    verifyAction: 'Verify code',
    save: 'Save password',
    pending: 'Processing…',
    resend: 'Resend code',
    wait: 'Try again in',
    seconds: 'seconds',
    forgot: 'Forgot password?',
    haveAccount: 'Already have an account?',
    newAccount: 'New here?',
    back: 'Back to sign in',
    preview: 'Explore preview',
    home: 'Home',
    unavailable:
      'Account services are unavailable. This request was not processed and no account was created.',
    notice:
      'Account services are not active yet. This form will not create an account until the server integration is ready.',
    devNotice:
      'Password signup without OTP is available only on the local development server for allowed emails. Product access remains closed.',
    invalid: 'Check the fields and try again.',
    expired: 'The verification request is missing or expired. Start again with your email.',
    rate_limited: 'Too many attempts. Wait before trying again.',
    credentials: 'The email or password could not be verified.',
    network: 'No connection. Your input was not sent; try again.',
    mismatch: 'Both passwords must match.',
    passwordHelp: '15–128 characters. Use a password unique to this service.',
    sessionRequired:
      'A valid verification session is required. Return to registration or recovery to continue.',
    continueEmail: 'Start with email',
    show: 'Show password',
    hide: 'Hide password',
  },
} as const;
